config:
  target: https://test.lpp.lithia.com/atlas
  phases:
    - duration: 300
      arrivalRate: 10
    - duration: 600
      arrivalRate: 100
    - duration: 300
      arrivalRate: 100

modules:
  console:
    logging: true

  final-stats: {}

json: ./results/'output.json'
# Add more reporting modules if needed.
