# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  ArtifactType: 'Container'
  ArtifactName: $[format('{0}-{1}', 'screenshots', variables['Build.BuildNumber'])]

steps:
  - task: NodeTool@0
    displayName: 'Use Node 16.x'
    inputs:
      versionSpec: 16.x

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: '$(Parameters.workingDir)'
      verbose: false

  - script: 'npm i && npx playwright install --with-deps chromium'
    workingDirectory: '$(Parameters.workingDirectory)'
    displayName: 'Install Playwright'

  - script: 'npx playwright test --project=AtlasWebE2E --grep @e2e --headed'
    workingDirectory: '$(Parameters.workingDirectory)'
    displayName: 'Run Playwright'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Screenshot'
    inputs:
      PathtoPublish: 'Playwright/helpers/screenshots' # Update the path to the screenshots directory
      ArtifactName: '$(ArtifactName)' # Use the ArtifactName variable
      publishLocation: '$(Parameters.ArtifactType)'

  - task: PublishTestResults@2
    displayName: 'Publish Atlas Web | End to End | TEST env E2E Test Results Results **/TEST-*.xml'
    inputs:
      testRunTitle: 'Atlas Web | End to End | TEST env E2E Test Results'
      buildPlatform: '$(Parameters.platform)'
      buildConfiguration: '$(Parameters.configuration)'
      publishRunAttachments: '$(Parameters.publishRunAttachments)'
    condition: succeededOrFailed()