execution:
  - concurrency: 100
    ramp-up: 2m
    hold-for: 3m
    script: validate_plan_endpoints
    scenario: validate_plan_endpoints
    report-file: /Taurus/Atlas/results/your_results.json  # Specify a custom directory and file for results
artifacts: false  # Disable artifacts generation


reporting:
  - module: console
  - module: final-stats
    summary: true
    percentiles: true
    failed-labels: false
    test-duration: true
    dump-csv: ./Taurus/Atlas/results/perf_result_csv.csv
  - module: junit-xml
    data-source: pass-fail
    filename: ./Taurus/Atlas/results/junit-result.xml
