// Storage state pre-auth pattern showcase.
// Demonstrates: project-level storageState loaded by playwright.config.js before the
// test starts. The test author writes assertions assuming the session is already live —
// no in-test login step required.
//
// The shipped helpers/login/the_internet_storage_state.json is a STUB (no cookies).
// In a corp setup the file is generated by a global-setup login flow and contains
// a valid session cookie. The PATTERN being demonstrated is the project wiring,
// not active session reuse against a public demo site.
//
// Target: https://the-internet.herokuapp.com

const { expect } = require("@playwright/test");
const { baseTest } = require("../../base/baseTest");
const { InternetDemoPage } = require("./internet_demo_page");

baseTest.describe.serial("Storage state pre-auth pattern @storage", () => {
  baseTest(
    "Project starts with pre-loaded session — no in-test login required",
    async ({ page, sweep, context }, testInfo) => {
      const demo = new InternetDemoPage(page);
      testInfo._pomClass = InternetDemoPage;
      await demo.goto();
      sweep();

      const cookies = await context.cookies();
      console.log(
        `[storageState] context loaded with ${cookies.length} pre-saved cookie(s)`
      );

      // In a real auth flow we'd assert against pre-authed UI here.
      // For the public demo, we just confirm the page loaded normally.
      await expect(demo.locators.pageHeader()).toBeVisible();
    }
  );
});
